# Loss

In [34]:

import sys
import numpy as np
import torch
from torch import matmul, diag, from_numpy
from torch.nn import Module, LogSoftmax

In [31]:
log_smax = LogSoftmax(dim=1)

future_predicted_timesteps = np.arange(1, 3)
predicted_future_Z = from_numpy(np.array([[1.2, 2.1, 2.8],
                               [0.1, 1.3, 2.2]]))
Z_future_timesteps = from_numpy(np.array([[1., 2., 3.],
                                          [0., 1., 2.]]))
loss = 0

In [33]:
predicted_future_Z[0]

tensor([1.2000, 2.1000, 2.8000], dtype=torch.float64)

In [21]:
matmul(Z_future_timesteps[0], predicted_future_Z[0].T)

tensor(13.8000, dtype=torch.float64)

In [ ]:
i = 0
for k in future_predicted_timesteps:
            loss -= diag(log_smax(matmul(Z_future_timesteps[k-1], predicted_future_Z[i].T))).sum(dim=0)
            i += 1

In [57]:
log_smax = LogSoftmax()
torch.manual_seed(42)
inp = 10*torch.randn(2, 2)
out = log_smax(inp)
inp, out

c:\Users\Kiarash\.conda\envs\ssl_py39\lib\site-packages\torch\nn\modules\module.py:1511: UserWarning: Implicit dimension choice for log_softmax has been deprecated. Change the call to include dim=X as an argument.
  return self._call_impl(*args, **kwargs)


(tensor([[3.3669, 1.2881],
         [2.3446, 2.3033]]),
 tensor([[-0.1179, -2.1967],
         [-0.6727, -0.7140]]))

# GRU

In [3]:
from torch.nn import GRU
import torch
rnn = GRU(input_size=512, hidden_size=256, num_layers=1, batch_first=True, bidirectional=False)

In [29]:
inp = torch.randn(8, 128, 512)
hidden = torch.randn(1, 8, 256)
y, h = rnn(inp, hidden)

tensor([[True, True, True, True, True, True, True, True, True, True, True, True,
         True, True, True, True, True, True, True, True, True, True, True, True,
         True, True, True, True, True, True, True, True, True, True, True, True,
         True, True, True, True, True, True, True, True, True, True, True, True,
         True, True, True, True, True, True, True, True, True, True, True, True,
         True, True, True, True, True, True, True, True, True, True, True, True,
         True, True, True, True, True, True, True, True, True, True, True, True,
         True, True, True, True, True, True, True, True, True, True, True, True,
         True, True, True, True, True, True, True, True, True, True, True, True,
         True, True, True, True, True, True, True, True, True, True, True, True,
         True, True, True, True, True, True, True, True, True, True, True, True,
         True, True, True, True, True, True, True, True, True, True, True, True,
         True, True, True, T